--- 
- 
  hosts: ejemplo
  name: "Shell module example"
  tasks: 
    - 
      name: "Check system information"
      register: os_info
      shell: "lsb_release -a"
    - 
      debug: 
        msg: "{{os_info.stdout_lines}}"
