---
- name: Shell module example
  hosts: example
  tasks:
  
- name: This command will change the working directory to somedir/.
  shell:
    cmd: hostname
    
  - debug:
    	msg: "{{os_info.stdout_lines}}"
